import { createRequire } from "module";
const require = createRequire(import.meta.url);
const {
    Bark
} = require("../bin/index.js");

const bark = new Bark({
    nThreads: 72,
    modelPath: '/media/denis.montes/Shared/models/bark/ggml_weights.bin',
    seed: Date.now(),
    device: 3
})

bark.generateAudio("This is an audio generated by bark.cpp")
bark.saveAudio("output.wav")